zk_server:
    container_name: zk_server
    image: zookeeper:3.4.6
    restart: always
    expose: 
        - "2181"
        - "2888"
        - "3888"
    ports:
        - "2181:2181"
        - "2888:2888"
        - "3888:3888"
    environment:
        - SERVICE_NAME=
    volumes:
        - config/zoo.cfg:/opt/zookeeper-3.4.6/conf/zoo.cfg
    command: start
#    command: /opt/zookeeper-3.4.6/bin/zkServer.sh start
#    links:
#        - zk2:zookeeper2
#        - zk3:zookeeper3
