zk_server:
    container_name: zk_server
    image: cjongseok/zookeeper:3.4.6
    restart: always
    ports:
        - "2181:2181"
        - "2181:2181/udp"
        - "2888:2888"
        - "2888:2888/udp"
        - "3888:3888"
        - "3888:3888/udp"
    environment:
        # Below env variables are automatically allocated by zk_env.sh
        - SERVICE_NAME=
        - ZK_SERVERS=
        - ZK_MYID=
        ##############################################################
        #volumes:
        #- config/zoo.cfg:/opt/zookeeper-3.4.6/conf/zoo.cfg
        #    command: start
#    command: /opt/zookeeper-3.4.6/bin/zkServer.sh start
#    links:
#        - zk2:zookeeper2
#        - zk3:zookeeper3
