#!/bin/bash
set -u

ZK_LAUNCHER=${ZK_HOME}/bin/zkServer.sh
ZK_DATA_DIR=${ZK_HOME}/data
ZK_MYID_FILE=${ZK_DATA_DIR}/myid


function func_configure_zookeeper(){
    local unset url
    local unset id
    local myid=$ZK_MYID
    local my_url=$SERVICE_NAME

    # add servers to zoo.cfg
    size=$(echo $ZK_SERVERS | awk '{print NF}')
    for ((id=1; id<=size; id++)); do
        url=$(echo $ZK_SERVERS | sed 's/"//g' | awk '{print $'"$((id))"'}')

        if [[ $url == $my_url ]]; then
            if [ -z "$myid" ]; then
                myid=$id
            fi

            # Set my server's ip as 0.0.0.0
            echo "server.$((id))=0.0.0.0:2888:3888" >> $ZK_CONF_FILE
        else
            # Set other server's as their Consul service name
            echo "server.$((id))=$url:2888:3888" >> $ZK_CONF_FILE
        fi
    done

    if [ ! -z "$myid" ]; then
        echo "set myid as $myid in ${ZK_MYID_FILE}"
        echo $myid > ${ZK_MYID_FILE}
    fi
}

function func_start_zookeeper(){
    $ZK_LAUNCHER start    
}


echo "my url is $SERVICE_NAME"
func_configure_zookeeper
func_start_zookeeper


